name: Learnery
version: 0.0.1
author: Blubywaff
main: blubywaff.learnery.Learnery
api-version: 1.16
commands:
  fly:
    descritpion: allows or disables your flight
    usage: /<command>
    permission: op
  god:
    description: prevents damage
    usage: /<command>
    permission: op
  speed:
    description: changes your speed
    usage: /<command> [speed]
    permission: op
  item:
    description: gives items
    usage: /<command> [item] [amount]
    permission: op
    aliases: [i]