name: Learnery
version: 0.0.1
author: Blubywaff
main: blubywaff.learnery.Learnery
api-version: 1.16
commands:
  fly:
    descritpion: allows or disables your flight
    usage: /<command>
    permission: op
  god:
    description: prevents damage
    usage: /<command>
    permission: op